name: sdk-go-client-webdav
title: SDK Go Client WebDAV
version: 1.0.0
summary: ctrlX WebDAV protocol sample written in Go for ctrlX CORE.
description: The sample demonstrates how to access to configuration files of a ctrlX CORE remotely using the WebDAV protocol.
confinement: strict # use 'strict' once you have the right plugs and slot
grade: stable
base: core22
type: app

architectures:
  - build-on: [amd64, arm64]
    build-for: [amd64]
  - build-on: [amd64, arm64]
    build-for: [arm64]

apps:
  client:
    command: bin/client
    plugs:
      - network
      - datalayer
    daemon: simple
    restart-condition: always
    passthrough:
      restart-delay: 10s

parts:
  client:
    plugin: go
    source: .
    build-snaps: ['go/1.22/stable']
    stage-packages:
      - ctrlx-datalayer
    build-packages:
      - on amd64:
          - libsystemd-dev
          - libzmq3-dev
          - pkg-config
      - on arm64:
          - libsystemd-dev:arm64
          - libzmq3-dev:arm64
        #- pkg-config:arm64
    override-build: |
      case $CRAFT_ARCH_TRIPLET in
        aarch64-linux-gnu)
          export GOARCH=arm64
          export GOARM=7
          export CGO_ENABLED=1
          export CC=aarch64-linux-gnu-gcc
          ;;
        amd64)
          export GOARCH=amd64
          ;;
      esac
      go build -buildvcs=false -o ../install/bin/ ./...

plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer
