name: sdk-ulimit-n-16384
title: SDK Ulimit
base: core22
version: 1.0.0
summary: Ulimit demo snap for ctrlX OS.
description: |
  This app demonstrates how you can increase the maximum number of open files with the command 'ulimit -n 16384' called by a command-chain wrapper.

grade: stable
confinement: strict
 
architectures:
  - build-on: [amd64, arm64]
    build-for: [amd64]
  - build-on: [amd64, arm64]
    build-for: [arm64]

parts:
  ulimit-script:
    plugin: dump
    source: ./ulimit-script
 
apps:
  ulimit:
    daemon: simple
    command: increase-ulimit.sh