#!/bin/bash

# SPDX-FileCopyrightText: Bosch Rexroth AG
#
# SPDX-License-Identifier: MIT

# This check-health script periodically checks our app (service) for it's service status.
# If the app not running or periodically restarted because of an crash, the health status will be reported to 'error', else 'okay'.
# 
# If the status is not 'okay', the commands sudo 'snap info {SNAPNAME}' or snap list return some informations about the app health.
# This app health information will also be reflected in ctrlX Datalayer (system/health) and visible to the end user in ctrlX Diagnostics.

# CHECK HEALTH CONFIGURATION

# Setup the name of your snap and the name of your app (please see 'snapcraft.yaml')
snap_name=ctrlx-monitor-health
app_name=app
check_interval_seconds=10

# CHECK HEALTH EXECUTION
service_name="${snap_name}.${app_name}"
echo starting health monitoring: ${service_name}
while :
do
    #fetch the status of the service
    status=$(snapctl services | grep -w ${service_name})

    if [[ $SNAP == "" ]]; then
        echo status: $status
    fi

    #enabled
    if [[ $status =~ " enabled " ]]; then
        #active
        if [[ $status =~ " active " ]]; then 
            if [[ $SNAP != "" ]]; then
                snapctl set-health okay 
            else
                echo app ´${service_name}´ running.
            fi
        
        #inactive
        elif [[ $status =~ " inactive " ]]; then        
            if [[ $SNAP != "" ]]; then
                echo app ´${service_name}´ stopped!
                snapctl set-health error "app stopped!"
            fi
        fi

    #disabled
    elif [[ $status =~ " disabled " ]]; then
        if [[ $SNAP != "" ]]; then
            echo app ´${service_name}´ disabled!
            snapctl set-health "app disabled!" 
        fi
    fi
       
    sleep ${check_interval_seconds}s
done

