#!/bin/bash

# MIT License
#
# Copyright (c) 2022 Bosch Rexroth AG
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


# This check-health script periodically checks our app (service) for it's service status.
# If the app not running or periodically restarted because of an crash, the health status will be reported to 'error', else 'okay'.
# 
# If the status is not 'okay', the commands sudo 'snap info {SNAPNAME}' or snap list return some informations about the app health.
# This app health information will also be reflected in ctrlX Datalayer (system/health) and visible to the end user in ctrlX Diagnostics.

# CHECK HEALTH CONFIGURATION

# Setup the name of your snap and the name of your app (please see 'snapcraft.yaml')
snap_name=ctrlx-monitor-health
app_name=app
check_interval_seconds=10

# CHECK HEALTH EXECUTION
service_name="${snap_name}.${app_name}"
echo starting health monitoring: ${service_name}
while :
do
    #fetch the status of the service
    status=$(snapctl services | grep -w ${service_name})

    if [[ $SNAP == "" ]]; then
        echo status: $status
    fi

    #enabled
    if [[ $status =~ " enabled " ]]; then
        #active
        if [[ $status =~ " active " ]]; then 
            if [[ $SNAP != "" ]]; then
                snapctl set-health okay 
            else
                echo app ´${service_name}´ running.
            fi
        
        #inactive
        elif [[ $status =~ " inactive " ]]; then        
            if [[ $SNAP != "" ]]; then
                echo app ´${service_name}´ stopped!
                snapctl set-health error "app stopped!"
            fi
        fi

    #disabled
    elif [[ $status =~ " disabled " ]]; then
        if [[ $SNAP != "" ]]; then
            echo app ´${service_name}´ disabled!
            snapctl set-health "app disabled!" 
        fi
    fi
       
    sleep ${check_interval_seconds}s
done

