---
version: 2
updates:
  - package-ecosystem: gomod
    directory: '/samples-go/**'
    schedule:
      interval: 'weekly'
  - package-ecosystem: npm
    directory: '/samples-node/**'
    allow:
      - dependency-type: 'production'
    schedule:
      interval: 'weekly'
  - package-ecosystem: nuget
    directory: '/samples-net/**'
    schedule:
      interval: 'weekly'
  - package-ecosystem: pip
    directory: '/samples-python/**'
    allow:
      - dependency-type: 'production'
    schedule:
      interval: 'weekly'
