---
version: 2
updates:
  - package-ecosystem: gomod
    directories:
      - '/samples-go/*'
    schedule:
      interval: 'monthly'
  - package-ecosystem: npm
    directories:
      - '/samples-node/*'
      - '!/samples-node/angular.multi-language'
    allow:
      - dependency-type: 'production'
    schedule:
      interval: 'monthly'
  - package-ecosystem: nuget
    directories:
      - '/samples-net/*'
    schedule:
      interval: 'monthly'
  - package-ecosystem: pip
    directories:
      - '/samples-python/*'
    allow:
      - dependency-type: 'production'
    schedule:
      interval: 'monthly'
