---
version: 2
updates:
  - package-ecosystem: gomod
    directory: '/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: npm
    directory: '/'
    allow:
      - dependency-type: 'production'
    schedule:
      interval: 'weekly'
  - package-ecosystem: nuget
    directory: '/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: pip
    directory: '/'
    allow:
      - dependency-type: 'production'
    schedule:
      interval: 'weekly'
