---
version: 2
updates:
  - package-ecosystem: gomod
    directories:
      - '/samples-go/*'
    schedule:
      interval: 'weekly'
  - package-ecosystem: npm
    directories:
      - '/samples-nodes/*'
    allow:
      - dependency-type: 'production'
    schedule:
      interval: 'weekly'
  - package-ecosystem: nuget
    directories:
      - '/samples-net/*'
    schedule:
      interval: 'weekly'
  - package-ecosystem: pip
    directories:
      - '/samples-python/*'
    allow:
      - dependency-type: 'production'
    schedule:
      interval: 'weekly'
