name: sdk-py-provider
title: SDK Python Provider
version: 1.0.0
summary: ctrlX Data Layer provider sample written in Python for ctrlX
description: |
  This sample shows how to provide data to the ctrlX Data Layer
base: core22
confinement: strict
grade: stable

architectures:
  - build-on: [amd64, arm64]
    build-for: [amd64]
  - build-on: [amd64, arm64]
    build-for: [arm64]

apps:
  provider:
    command: bin/main.py
    plugs:
      - network
      - datalayer
    daemon: simple
    restart-condition: always
    passthrough:
      restart-delay: 30s

parts:
  provider:
    plugin: python
    source: .
    stage-packages:
      - ctrlx-datalayer
      - libzmq5

  bfbs:
    plugin: dump
    source: ./bfbs

plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer
