name: sdk-py-provider
version: 2.4.0
summary: ctrlX Data Layer provider sample written in Python for ctrlX
title: sdk-py-provider
description: |
  This sample shows how to provide data to the ctrlX Data Layer
base: core22
confinement: strict
grade: stable

apps:
  provider:
    command: bin/main.py
    plugs:
      - network
      - datalayer
    daemon: simple
    restart-condition: always
    passthrough:   
      restart-delay: 10s

parts:
  provider:
    plugin: python
    source: .
    stage-packages:
      - libzmq5
      - ctrlx-datalayer

  bfbs:
    plugin: dump
    source: ./bfbs 

  mddb:
    plugin: dump
    source: ./mddb 
      
plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer