name: sdk-py-logbook
title: SDK Python Logbook
version: 1.0.0
summary: Logbook sample written in Python for ctrlX
description: |
  This sample shows how to log with different log levels
base: core22
confinement: strict
grade: stable

apps:
  logbook:
    command: bin/main.py
    plugs:
      - network
      - datalayer
    daemon: simple
    restart-condition: always
    passthrough:
      restart-delay: 30s

parts:
  logbook:
    plugin: python
    source: .
    stage-packages:
      - libsystemd-dev

plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer
