name: sdk-py-logbook
title: SDK Python Logbook
version: 1.0.0
summary: Logbook sample written in Python for ctrlX
description: |
  This sample shows how to log with different log levels
base: core22
confinement: strict
grade: stable

apps:
  logbook:
    command: bin/main.py
    plugs:
      - network
      - datalayer
    daemon: simple
    restart-condition: always
    passthrough:
      restart-delay: 30s

parts:
  logbook:
    plugin: python
    source: .
    build-environment:
      - SNAPCRAFT_PYTHON_INTERPRETER: python3.10
      - GITHUB_CYSYSTEMD: https://github.com/mosquito/cysystemd/releases/download/1.5.4
      - PLATFORM_CYSYSTEMD: manylinux_2_28_x86_64
      - TARGET_PATH: ${SNAPCRAFT_PART_INSTALL}/lib/${SNAPCRAFT_PYTHON_INTERPRETER}/site-packages 
    stage-packages:
      - libsystemd-dev
    override-build: |
      snapcraftctl build
      case $SNAPCRAFT_ARCH_TRIPLET in
        aarch64-linux-gnu)
          export PLATFORM_CYSYSTEMD=manylinux_2_28_aarch64
          ;;
        amd64)
          ;;
      esac
      pip3 install --platform=${PLATFORM_CYSYSTEMD} --only-binary=:all: --target ${TARGET_PATH} $GITHUB_CYSYSTEMD/cysystemd-1.5.4-cp310-cp310-${PLATFORM_CYSYSTEMD}.whl
      
plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer
