c:\ctrlx-automation-sdk\bin\fbs2plc\win-x64\fbs2plc.exe ^
-verbose ^
-src c:\ctrlx-automation-sdk\samples-cpp\datalayer.provider.all-data\sampleSchema.fbs ^
-dest FBS/sampleSchema ^
-flatc c:\ctrlx-automation-sdk\bin\oss.flatbuffers\win-msvc-x64\release\flatc.exe ^
-plc "c:\Program Files\Rexroth\ctrlX WORKS\Studio\Common\ctrlX-PLC-Engineering.exe" ^
-addr localhost ^
-port 9002 ^
-timeout 5 ^
-plcWaitAfterStart 60 ^
-libTitle "SampleSchema Flatbuffers Handling" ^
-libCompany "Bosch Rexroth AG" ^
-libVersion 1.0.0.0 ^
-libReleased ^
-libAuthor "Bosch Rexroth AG" ^
-libPlaceHolder "SampleSchema" ^
-libDescription "Function block to read/write flatbuffers described in sampleSchema.fbs." ^
-libDefaultNamespace sampleSchema