/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/current/userguide/multi_project_builds.html
 */

fun String?.firstNonEmpty(): String? {
    if (this.isNullOrBlank()) return null
    return this.trim()
}

fun applyProxyFromEnv() {
    fun parseProxy(url: String): Pair<String, String>? {
        val normalized = url
            .removePrefix("http://")
            .removePrefix("https://")
            .substringBefore("/")
        if (normalized.isBlank()) return null

        val host = normalized.substringBefore(":").trim()
        val port = normalized.substringAfter(":", "8080").trim()
        if (host.isEmpty() || port.isEmpty()) return null
        return host to port
    }

    val httpProxy = System.getenv("HTTP_PROXY").firstNonEmpty()
        ?: System.getenv("http_proxy").firstNonEmpty()
    val httpsProxy = System.getenv("HTTPS_PROXY").firstNonEmpty()
        ?: System.getenv("https_proxy").firstNonEmpty()

    httpProxy?.let {
        parseProxy(it)?.let { (host, port) ->
            System.setProperty("http.proxyHost", host)
            System.setProperty("http.proxyPort", port)
        }
    }

    httpsProxy?.let {
        parseProxy(it)?.let { (host, port) ->
            System.setProperty("https.proxyHost", host)
            System.setProperty("https.proxyPort", port)
        }
    }

    val noProxy = System.getenv("NO_PROXY").firstNonEmpty()
        ?: System.getenv("no_proxy").firstNonEmpty()
    noProxy?.let {
        val nonProxyHosts = it.split(",")
            .map(String::trim)
            .filter(String::isNotEmpty)
            .joinToString("|") { host ->
                when {
                    host == "*" -> "*"
                    host.startsWith(".") -> "*${host}"
                    else -> host
                }
            }
        if (nonProxyHosts.isNotEmpty()) {
            System.setProperty("http.nonProxyHosts", nonProxyHosts)
            System.setProperty("https.nonProxyHosts", nonProxyHosts)
        }
    }
}

applyProxyFromEnv()

pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

rootProject.name = "datalayer.provider.simple"
include("app")
