# Getting started
# See https://snapcraft.io/docs/getting-started
# Snapcraft references
# See https://snapcraft.io/docs/snapcraft-yaml-reference

name: sdk-cpp-hello-world
title: SDK C++ Hello World
version: 1.0.0
grade: stable
summary: Print 'Hello World' to console output
description: |
  This App is a simple example to show how to make an App.
base: core22
confinement: strict

architectures:
  - build-on: [amd64, arm64]
    build-for: [amd64]
  - build-on: [amd64, arm64]
    build-for: [arm64]

# define how apps & services are exposed to host system
apps:
  app:
    command: HelloWorld
    # interfaces to connect to https://snapcraft.io/docs/supported-interfaces
    plugs:
      - network
    daemon: simple
    restart-condition: always
    passthrough:
      restart-delay: 10s

#  describes how to import, and potentially build, each required part of the snap:
parts:
  helloworld:
    plugin: dump
    source: ./generated/build
