name: sdk-py-provider-alldata
title: SDK Python Provider All Data
version: 1.0.0
summary: ctrlX Data Layer provider sample in Python
description: |
  ctrlX Data Layer provider in Python publishing nodes of all data types
base: core22
confinement: strict
grade: stable

apps:
  provider:
    command: bin/main.py
    plugs:
      - network
      - datalayer
    daemon: simple
    restart-condition: always
    passthrough:
      restart-delay: 30s

parts:
  provider:
    plugin: python
    source: .
    stage-packages:
      - libzmq5
      - ctrlx-datalayer

plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer
