name: sdk-py-calc
title: SDK Python Calculation
version: 1.0.0
summary: Makes a calculation in Python
description: 'Sample App in Python using ctrlX Data Layer subscriptions'
base: core22
confinement: strict
grade: stable

apps:
  client:
    command: bin/main.py
    plugs:
      - network
      - datalayer
    daemon: simple

parts:
  client:
    plugin: python
    source: .
    stage-packages:
      - libzmq5
      - ctrlx-datalayer

# describes which interface slots are supported by defining the plugs
plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer
