name: sdk-py-calc
title: SDK Python Calculation
version: 1.0.0
summary: Makes a calculation in Python
description: 'Sample App in Python using ctrlX Data Layer subscriptions'
base: core22
confinement: strict
grade: stable

architectures:
  - build-on: [amd64, arm64]
    build-for: [amd64]
  - build-on: [amd64, arm64]
    build-for: [arm64]

apps:
  client:
    command: bin/main.py
    plugs:
      - network
      - datalayer
    daemon: simple

parts:
  client:
    plugin: python
    source: .
    stage-packages:
      - ctrlx-datalayer

# describes which interface slots are supported by defining the plugs
plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer

lint:
  ignore:
    - library:
      - usr/lib/aarch64-linux-gnu/libcomm_datalayer.so.*
      - usr/lib/x86_64-linux-gnu/libcomm_datalayer.so.*
