// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod pkg {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};
#[allow(unused_imports, dead_code)]
pub mod sample {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};
#[allow(unused_imports, dead_code)]
pub mod schema {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

pub enum InertialValueOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct InertialValue<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for InertialValue<'a> {
  type Inner = InertialValue<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> InertialValue<'a> {
  pub const VT_X: flatbuffers::VOffsetT = 4;
  pub const VT_Y: flatbuffers::VOffsetT = 6;
  pub const VT_Z: flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    InertialValue { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args InertialValueArgs
  ) -> flatbuffers::WIPOffset<InertialValue<'bldr>> {
    let mut builder = InertialValueBuilder::new(_fbb);
    builder.add_z(args.z);
    builder.add_y(args.y);
    builder.add_x(args.x);
    builder.finish()
  }

  pub fn unpack(&self) -> InertialValueT {
    let x = self.x();
    let y = self.y();
    let z = self.z();
    InertialValueT {
      x,
      y,
      z,
    }
  }

  #[inline]
  pub fn x(&self) -> i16 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i16>(InertialValue::VT_X, Some(0)).unwrap()}
  }
  #[inline]
  pub fn y(&self) -> i16 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i16>(InertialValue::VT_Y, Some(0)).unwrap()}
  }
  #[inline]
  pub fn z(&self) -> i16 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i16>(InertialValue::VT_Z, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for InertialValue<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<i16>("x", Self::VT_X, false)?
     .visit_field::<i16>("y", Self::VT_Y, false)?
     .visit_field::<i16>("z", Self::VT_Z, false)?
     .finish();
    Ok(())
  }
}
pub struct InertialValueArgs {
    pub x: i16,
    pub y: i16,
    pub z: i16,
}
impl<'a> Default for InertialValueArgs {
  #[inline]
  fn default() -> Self {
    InertialValueArgs {
      x: 0,
      y: 0,
      z: 0,
    }
  }
}

pub struct InertialValueBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> InertialValueBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_x(&mut self, x: i16) {
    self.fbb_.push_slot::<i16>(InertialValue::VT_X, x, 0);
  }
  #[inline]
  pub fn add_y(&mut self, y: i16) {
    self.fbb_.push_slot::<i16>(InertialValue::VT_Y, y, 0);
  }
  #[inline]
  pub fn add_z(&mut self, z: i16) {
    self.fbb_.push_slot::<i16>(InertialValue::VT_Z, z, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> InertialValueBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    InertialValueBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<InertialValue<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for InertialValue<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("InertialValue");
      ds.field("x", &self.x());
      ds.field("y", &self.y());
      ds.field("z", &self.z());
      ds.finish()
  }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct InertialValueT {
  pub x: i16,
  pub y: i16,
  pub z: i16,
}
impl Default for InertialValueT {
  fn default() -> Self {
    Self {
      x: 0,
      y: 0,
      z: 0,
    }
  }
}
impl InertialValueT {
  pub fn pack<'b, A: flatbuffers::Allocator + 'b>(
    &self,
    _fbb: &mut flatbuffers::FlatBufferBuilder<'b, A>
  ) -> flatbuffers::WIPOffset<InertialValue<'b>> {
    let x = self.x;
    let y = self.y;
    let z = self.z;
    InertialValue::create(_fbb, &InertialValueArgs{
      x,
      y,
      z,
    })
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `InertialValue`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_inertial_value_unchecked`.
pub fn root_as_inertial_value(buf: &[u8]) -> Result<InertialValue, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<InertialValue>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `InertialValue` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_inertial_value_unchecked`.
pub fn size_prefixed_root_as_inertial_value(buf: &[u8]) -> Result<InertialValue, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<InertialValue>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `InertialValue` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_inertial_value_unchecked`.
pub fn root_as_inertial_value_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<InertialValue<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<InertialValue<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `InertialValue` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_inertial_value_unchecked`.
pub fn size_prefixed_root_as_inertial_value_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<InertialValue<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<InertialValue<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a InertialValue and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `InertialValue`.
pub unsafe fn root_as_inertial_value_unchecked(buf: &[u8]) -> InertialValue {
  flatbuffers::root_unchecked::<InertialValue>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed InertialValue and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `InertialValue`.
pub unsafe fn size_prefixed_root_as_inertial_value_unchecked(buf: &[u8]) -> InertialValue {
  flatbuffers::size_prefixed_root_unchecked::<InertialValue>(buf)
}
#[inline]
pub fn finish_inertial_value_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<InertialValue<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_inertial_value_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>, root: flatbuffers::WIPOffset<InertialValue<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod schema
}  // pub mod sample
}  // pub mod pkg

