# Getting started
# See https://snapcraft.io/docs/getting-started
# Snapcraft references
# See https://snapcraft.io/docs/snapcraft-yaml-reference

name: sdk-cpp-client-sub
title: SDK C++ Client Subscription
version: 1.0.0
grade: stable
summary: SDK sample app in cpp - subscribes ctrlX Data Layer nodes
description: |
  This sample demonstrates how to use ctrlX Data Layer subscriptions on Datalayer.
  It subscribes the nodes: framework/metrics/system/cpu-utilisation-percent and .../memavailable-mb.
  If a value of a node has changed it writes the new value to the console.
base: core22
confinement: strict

# define how apps & services are exposed to the target operating system
apps:
  app:
    command: datalayerClientSub
    # interfaces to connect to https://snapcraft.io/docs/supported-interfaces
    plugs:
      - network
      - datalayer
    daemon: simple
    restart-condition: always
    passthrough:
      restart-delay: 10s

parts:
  app:
    plugin: dump
    source: ./generated/build
    stage-packages:
      - libzmq5
      - ctrlx-datalayer

# describes which interface slots are supported by defining the plugs
plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer
