# Getting started
# See https://snapcraft.io/docs/getting-started
# Snapcraft references
# See https://snapcraft.io/docs/snapcraft-yaml-reference

name: sdk-cpp-diagnostics-logbook
title: SDK C++ Diagnostics Logbook
version: 1.0.0
grade: stable
summary: Writes messages to journald and the ctrlX logbook
description: |
  This is a simple App to show how messages with different log levels are written to journald and the ctrlX logbook.
base: core22
confinement: strict

architectures:
  - build-on: [amd64, arm64]
    build-for: [amd64]
  - build-on: [amd64, arm64]
    build-for: [arm64]

# define how apps & services are exposed to host system
apps:
  logbook:
    command: logbook
    # interfaces to connect to https://snapcraft.io/docs/supported-interfaces
    plugs: []
    daemon: simple
    restart-condition: always
    passthrough:
      restart-delay: 10s

#  describes how to import, and potentially build, each required part of the snap:
parts:
  logbook:
    plugin: dump
    source: ./generated/build
