# Getting started
# See https://snapcraft.io/docs/getting-started
# Snapcraft references
# See https://snapcraft.io/docs/snapcraft-yaml-reference

name: sdk-cpp-diagnosis
title: SDK C++ Diagnosis
version: 1.0.0
grade: stable
summary: Sample app for processing diagnosis data via ctrlX Data Layer
description: |
  This app will call diagnosis functions via ctrlX Data Layer
base: core22
confinement: strict

# define how apps & services are exposed to host system
apps:
  app:
    command: datalayerDiagnosis
    # Interfaces to connect to https://snapcraft.io/docs/supported-interfaces
    # TODO Werden diese Interfaces alle benötigt???
    plugs:
      - network
      - network-status
      - network-bind
      - process-control
      - datalayer
    daemon: simple
    restart-condition: always
    passthrough:
      restart-delay: 10s

parts:
  app:
    plugin: dump
    source: ./generated/build
    stage-packages:
      - libzmq5
      - ctrlx-datalayer

  resourcesdiagnosis:
    plugin: dump
    source: ./resources/diagnostics
    organize:
      '*': ./resources/diagnostics/

# describes which interface slots are supported by defining the plugs
plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer
