# Getting started
# See https://snapcraft.io/docs/getting-started
# Snapcraft references
# See https://snapcraft.io/docs/snapcraft-yaml-reference

name: sdk-cpp-ecat-io
title: SDK C++ EtherCAT I/O
version: 1.0.0
grade: stable
summary: Sample app for copying EtherCAT I/Os.
description: |
  This app will copy EtherCAT digital inputs to outputs.
base: core22
confinement: strict

# define how apps & services are exposed to host system
apps:
  app:
    command: datalayerEcatio
    # interfaces to connect to https://snapcraft.io/docs/supported-interfaces
    plugs:
      - network
      - datalayer
      - system-files
    daemon: simple
    passthrough:
      restart-condition: always
      restart-delay: 10s

parts:
  app:
    plugin: dump
    source: ./generated/build
    stage-packages:
      - libzmq5
      - ctrlx-datalayer

# describes which interface slots are supported by defining the plugs
plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer

  system-files:
    interface: system-files
    write:
      - /dev/shm
