/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.2/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

fun RepositoryHandler.artifactoryRepoIfEnabled() {
     val useCustomRepo = System.getenv("BUILD_USER")
     if (!useCustomRepo.isNullOrEmpty()) {
        maven {
            name = "Artifactory"
            url = uri(System.getenv("JAVA_ARTIFACTORY_URL"))
            credentials {
                username = System.getenv("BUILD_USER")
                password = System.getenv("BUILD_PASS")
            }
        }    
    }
}

fun RepositoryHandler.localRepo() {
    flatDir { 
        //dirs("../../../java") 
        dirs("../java") 
    }
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()

    artifactoryRepoIfEnabled()

    localRepo()
    // flatDir { 
    //     //dirs("../libs") 
    //     dirs("../../java") 
    // }
}

dependencies {

    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)


    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    // https://mvnrepository.com/artifact/com.google.flatbuffers/flatbuffers-java
    implementation(libs.flatbuffers.java)
    
    //ctrlX Datalayer
    implementation(libs.ctrlx.datalayer)
    implementation(libs.ctrlx.datalayer.fbs)
}
    

application {
    // Define the main class for the application.
    mainClass.set("datalayer.provider.sub.App")
}

tasks.test {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

tasks.jar {
     manifest {
         attributes(mapOf("Implementation-Title" to rootProject.name,
                          "Implementation-Version" to project.version,
                          "Bundle-License" to "MIT",
                          "Bundle-Vendor" to "Bosch Rexroth AG",
                          "Bundle-Description" to "ctrlX Data Layer provider sample written in Java for ctrlX OS.",
                          "Main-Class" to "datalayer.provider.sub.App",
                          "Bundle-Classpath" to ".,jar/*,/jar/*",
                          ))
     }
     //archiveFileName.set("${project.group}.${rootProject.name}-${project.version}.jar")

    val dependenciesRuntime = configurations
                            .runtimeClasspath
                            .get()
                            .map(::zipTree)

    val dependenciesCompile = configurations
                            .compileClasspath
                            .get()
                            .map(::zipTree)
    from(dependenciesRuntime)
    from(dependenciesCompile)
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}