# Getting started
# See https://snapcraft.io/docs/getting-started
# Snapcraft references
# See https://snapcraft.io/docs/snapcraft-yaml-reference

name: sdk-cpp-remote-scheduler
title: SDK C++ Remote Scheduler
version: 1.0.0
grade: stable

contact: https://github.com/boschrexroth/ctrlx-automation-sdk
license: MIT
donation: https://github.com/boschrexroth/ctrlx-automation-sdk
issues: https://github.com/boschrexroth/ctrlx-automation-sdk/issues
source-code: https://github.com/boschrexroth/ctrlx-automation-sdk
website: https://github.com/boschrexroth/ctrlx-automation-sdk

summary: Implements an external trigger for the Scheduler
description: |
  This is a simple sample that shows how an external trigger can be used for the Scheduler service.
base: core24
confinement: strict

platforms:
  amd64:
  arm64:
    build-on: [amd64, arm64]
    build-for: [arm64]

build-snaps:
  - core24

# define how apps & services are exposed to host system
apps:
  app:
    command: scheduler.remote
    # interfaces to connect to https://snapcraft.io/docs/supported-interfaces
    plugs:
      - network
      - datalayer
      - datalayer-shm
      - process-control
    daemon: simple
    passthrough:
      restart-condition: always
      restart-delay: 10s    
    environment:
      TRACE_ENABLE_STDOUT: "true"
      TRACE_ENABLE_UNITS: "sdk.common.remote-scheduler"

parts:
  bundle:
    source: ./generated/build
    plugin: dump
    stage-packages:
      - ctrlx-datalayer
      - ctrlx-scheduler

# describes which interface slots are supported by defining the plugs
plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer
  datalayer-shm:
    interface: shared-memory
    shared-memory: datalayer-shm