// automatically generated by the FlatBuffers compiler, do not modify

package pkg.sample.schema;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class InertialValue extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static InertialValue getRootAsInertialValue(ByteBuffer _bb) { return getRootAsInertialValue(_bb, new InertialValue()); }
  public static InertialValue getRootAsInertialValue(ByteBuffer _bb, InertialValue obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public InertialValue __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public short x() { int o = __offset(4); return o != 0 ? bb.getShort(o + bb_pos) : 0; }
  public short y() { int o = __offset(6); return o != 0 ? bb.getShort(o + bb_pos) : 0; }
  public short z() { int o = __offset(8); return o != 0 ? bb.getShort(o + bb_pos) : 0; }

  public static int createInertialValue(FlatBufferBuilder builder,
      short x,
      short y,
      short z) {
    builder.startTable(3);
    InertialValue.addZ(builder, z);
    InertialValue.addY(builder, y);
    InertialValue.addX(builder, x);
    return InertialValue.endInertialValue(builder);
  }

  public static void startInertialValue(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addX(FlatBufferBuilder builder, short x) { builder.addShort(0, x, 0); }
  public static void addY(FlatBufferBuilder builder, short y) { builder.addShort(1, y, 0); }
  public static void addZ(FlatBufferBuilder builder, short z) { builder.addShort(2, z, 0); }
  public static int endInertialValue(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishInertialValueBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedInertialValueBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public InertialValue get(int j) { return get(new InertialValue(), j); }
    public InertialValue get(InertialValue obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public InertialValueT unpack() {
    InertialValueT _o = new InertialValueT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(InertialValueT _o) {
    short _oX = x();
    _o.setX(_oX);
    short _oY = y();
    _o.setY(_oY);
    short _oZ = z();
    _o.setZ(_oZ);
  }
  public static int pack(FlatBufferBuilder builder, InertialValueT _o) {
    if (_o == null) return 0;
    return createInertialValue(
      builder,
      _o.getX(),
      _o.getY(),
      _o.getZ());
  }
}

