ctrlX Data Layer API for Python: MetadataBuilder Class Reference
MetadataBuilder Class Reference
Public Member Functions
__init__ (self, AllowedOperation allowed=AllowedOperation.BROWSE, str description="", str description_url="")
add_extensions (self, str key, str val)
add_localization_description (self, str ident, str txt)
add_localization_display_name (self, str ident, str txt)
add_reference (self, ReferenceType t, str addr)
Variant build (self)
set_display_format (self, DisplayFormat.DisplayFormat.Auto f)
set_display_name (self, str name)
set_node_class (self, NodeClass node_class)
set_operations (self, AllowedOperation allowed=AllowedOperation.NONE)
set_unit (self, str unit)
Static Public Member Functions
Variant create_metadata (str name, str description, str unit, str description_url, NodeClass node_class, bool read_allowed, bool write_allowed, bool create_allowed, bool delete_allowed, bool browse_allowed, str type_path, dict references=None)
Detailed Description
Builds a flatbuffer provided with the metadata information for a Data Layer node.
Definition at line 78 of file metadata_utils.py.
Constructor & Destructor Documentation
__init__()
__init__ (self, AllowedOperation allowed = AllowedOperation.BROWSE, str description = "", str description_url = "")
generate MetadataBuilder
Definition at line 129 of file metadata_utils.py.
References MetadataBuilder.__allowed, MetadataBuilder.__description, MetadataBuilder.__description_url, MetadataBuilder.__descriptions, MetadataBuilder.__displayformat, MetadataBuilder.__displaynames, MetadataBuilder.__extensions, MetadataBuilder.__name, MetadataBuilder.__node_class, MetadataBuilder.__references, MetadataBuilder.__unit, and MetadataBuilder.set_operations().
Member Function Documentation
add_extensions()
add_extensions (self, str key, str val)
add extension
Definition at line 240 of file metadata_utils.py.
References MetadataBuilder.__extensions.
add_localization_description()
add_localization_description (self, str ident, str txt)
add localization of descriptions
Definition at line 246 of file metadata_utils.py.
References MetadataBuilder.__descriptions.
add_localization_display_name()
add_localization_display_name (self, str ident, str txt)
add localization of display names
Definition at line 252 of file metadata_utils.py.
References MetadataBuilder.__add_extension(), MetadataBuilder.__add_local_text(), MetadataBuilder.__add_reference(), MetadataBuilder.__allowed, MetadataBuilder.__build_local_texts(), MetadataBuilder.__descriptions, MetadataBuilder.__displaynames, MetadataBuilder.__extensions, MetadataBuilder.__is_allowed(), and MetadataBuilder.__references.
add_reference()
add_reference (self, ReferenceType t, str addr)
add reference
Definition at line 234 of file metadata_utils.py.
References MetadataBuilder.__references.
build()
Variant build (self)
Build Metadata as Variant.
Returns
Variant Metadata
Definition at line 149 of file metadata_utils.py.
References MetadataBuilder.__build_descriptions(), MetadataBuilder.__build_display_names(), MetadataBuilder.__build_extensions(), MetadataBuilder.__build_operations(), MetadataBuilder.__build_references(), MetadataBuilder.__buildV2(), MetadataBuilder.__description, MetadataBuilder.__description_url, MetadataBuilder.__displayformat, MetadataBuilder.__name, MetadataBuilder.__node_class, and MetadataBuilder.__unit.
create_metadata()
Variant create_metadata (str name, str description, str unit, str description_url, NodeClass node_class, bool read_allowed, bool write_allowed, bool create_allowed, bool delete_allowed, bool browse_allowed, str type_path, dict references = None) static
Definition at line 90 of file metadata_utils.py.
set_display_format()
set_display_format (self, DisplayFormat.DisplayFormat.Auto f)
set display format
Definition at line 227 of file metadata_utils.py.
References MetadataBuilder.__displayformat.
set_display_name()
set_display_name (self, str name)
set the display name
Definition at line 206 of file metadata_utils.py.
References MetadataBuilder.__name.
set_node_class()
set_node_class (self, NodeClass node_class)
set the node class
Definition at line 213 of file metadata_utils.py.
References MetadataBuilder.__node_class.
set_operations()
set_operations (self, AllowedOperation allowed = AllowedOperation.NONE)
set allowed operations
Definition at line 220 of file metadata_utils.py.
References MetadataBuilder.__allowed.
Referenced by MetadataBuilder.__init__().
set_unit()
set_unit (self, str unit)
set the unit
Definition at line 199 of file metadata_utils.py.
References MetadataBuilder.__unit.