# Getting started
# See https://snapcraft.io/docs/getting-started
# Snapcraft references
# See https://snapcraft.io/docs/snapcraft-yaml-reference
version: '1.0.0'
name: ctrlx-dotnet-hello-world
summary: Hello World sample written in .NET for ctrlX.
description: |
  Programm is prompting "Hello World" to standard output. Enter 'sudo snap logs ctrlx-dotnet-hello-world.app -f | more' to see the output.
confinement: strict 
#confinement: devmode 
#icon: assets/icons/ICONHERE.png
grade: stable  # must be 'stable' to release into candidate/stable channels
base: core20
type: app

apps:
  app:
    command: hello.world
    daemon: simple
    restart-condition: always
    passthrough:   
      restart-delay: 10s
    
    environment:
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 'true'
 
parts:
  app:
    plugin: dump
    source: ./publish/${SNAPCRAFT_TARGET_ARCH}
