__version__ = "0.0.1"
__description__ = "Sample for calculations with data from the ctrlX Data Layer"
__author__ = "Fantastic Python Developers"
__licence__ = "MIT License"
__copyright__ = "Copyright (c) 2021 Bosch Rexroth AG"