name: sdk-py-client
version: 2.1.0
summary: Data Layer client sample written in Python for ctrlX.
title: sdk-py-client
description:  |
  The sample demonstrates how to read values from ctrlX Data Layer tree and write out the values to console.
base: core20
confinement: strict
grade: stable

apps:
  client:
    command: bin/main.py
    plugs:
      - network
      - datalayer
    daemon: simple
    passthrough:
      restart-condition: always
      restart-delay: 10s 
      
parts:
  client:
    plugin: python
    source: .

  datalayerdeb:
      plugin: dump
      source: ./tmp/ctrlx-datalayer.deb
      source-type: deb
      stage-packages:
        - libzmq5
      override-pull: |
        mkdir -p ../../../tmp/
        cp ../../../../../deb/ctrlx-datalayer-1.*.*.deb ../../../tmp/ctrlx-datalayer.deb
        snapcraftctl pull
      override-prime: |
        rm -rf ../tmp
        snapcraftctl prime

plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer 
