name: sdk-py-client
version: 2.4.0
summary: ctrlX Data Layer client sample written in Python for ctrlX CORE.
title: sdk-py-client
description:  |
  The sample demonstrates how to read values from ctrlX Data Layer tree and write out the values to console.
base: core22
confinement: strict
grade: stable

apps:
  client:
    command: bin/main.py
    plugs:
      - network
      - datalayer
    daemon: simple
    passthrough:
      restart-condition: always
      restart-delay: 10s 
      
parts:
  client:
    plugin: python
    source: .
    stage-packages:
      - libzmq5
      - ctrlx-datalayer

plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer 
