name: sdk-py-browse
version: 2.4.0
summary: ctrlX Data Layer browse sample written in Python for ctrlX
title: sdk-py-browse
description: |
  This sample demonstrates how to browse a ctrlX Data Layer tree
base: core22
confinement: strict
grade: stable

apps:
  client:
    command: bin/main.py
    plugs:
      - network
      - datalayer
    daemon: simple
    passthrough:
      restart-condition: always
      restart-delay: 10s 

parts:
  client:
    plugin: python
    source: .
    stage-packages:
      - libzmq5
      - ctrlx-datalayer

plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer 
