name: sdk-tpm2-webserver
title: SDK TPM2 Webserver
base: core22
version: 1.0.0
summary: A snap containing a tpm2 based openssl server for ctrlX CORE.
description: |
  This app demonstrates how you can access the TPM2.

grade: devel
confinement: strict

architectures:
  - build-on: [amd64, arm64]
    build-for: [amd64]
  - build-on: [amd64, arm64]
    build-for: [arm64]

plugs:
  tpm2-socket:
    interface: content
    content: tpm2-socket
    target: $SNAP_DATA/tpm2-socket
  system-configuration:
    interface: content
    content: system-configuration
    target: $SNAP_DATA/system-configuration
slots:
  package-certificates:
    interface: content
    content: package-certificates
    source:
      write:
      - $SNAP_COMMON/package-certificates/${CRAFT_PROJECT_NAME}
  package-assets:
    interface: content
    content: package-assets
    source:
      read:
      - $SNAP/package-assets/${CRAFT_PROJECT_NAME}

parts:
  configs:
    plugin: dump
    source: ./configs
    organize:
      'package-assets/*': package-assets/${CRAFT_PROJECT_NAME}/
  tpm2-tools:
    plugin: autotools
    build-environment:
      - LDFLAGS: "$LDFLAGS -Wl,-rpath-link,$CRAFT_STAGE/lib"
    source: https://github.com/tpm2-software/tpm2-tools
    source-type: git
    source-tag: "5.2"
    build-packages:
    - pandoc
    - pkg-config
    - autoconf-archive
    - autoconf
    - to amd64:
      - libcmocka-dev
      - libcurl4-openssl-dev
      - libssl-dev
      - libtool
      - uuid-dev
    - to arm64:
      - libcmocka-dev:arm64
      - libcurl4-openssl-dev:arm64
      - libssl-dev:arm64
      - libtool:arm64
      - uuid-dev:arm64
    stage-packages:
    - to amd64:
      - libcurl4
    - to arm64:
      - libcurl4:arm64
    prime:
      - -include
    after:
      - tpm2-tss
    override-build: |
      ACLOCAL_PATH="/usr/share/gnulib/m4" ./bootstrap
      ./configure --prefix=$CRAFT_PART_INSTALL/usr/ --host=$CRAFT_ARCH_TRIPLET
      #craftctl default
      # Run all tests shipped by default
      make check -j$(nproc)
      make install

  tpm2-tss:
    plugin: make
    source: https://github.com/tpm2-software/tpm2-tss
    source-type: git
    source-tag: 3.2.0
    build-packages:
    - gcc
    - g++
    - doxygen
    - pkg-config
    - autoconf
    - autoconf-archive
    - to amd64:
      - libtool
      - libltdl-dev
      - libjson-c-dev
      - libgcrypt20-dev
      - liburiparser-dev
      - libcurl4-openssl-dev
      - libssl-dev
    - to arm64:
      - libtool:arm64
      - libltdl-dev:arm64
      - libjson-c-dev:arm64
      - libgcrypt20-dev:arm64
      - liburiparser-dev:arm64
      - libcurl4-openssl-dev:arm64
      - libssl-dev:arm64
    prime:
      - -include
    override-build: |
      ACLOCAL_PATH="/usr/share/gnulib/m4" ./bootstrap #https://github.com/tpm2-software/tpm2-tss/commit/d1106347ef2f8e7296f1bd6af7aa6e046f6a5a38
      ./configure --prefix=$CRAFT_PART_INSTALL/usr/ --host=$CRAFT_ARCH_TRIPLET
      make check -j$(nproc) || cat ./test-suite.log
      make install
      #chmod g-s $CRAFT_PART_INSTALL/usr/var/run/tpm2-tss/eventlog
      #chmod g-s $CRAFT_PART_INSTALL/usr/var/lib/tpm2-tss/system/keystore #https://github.com/tpm2-software/tpm2-tss/commit/811e451c9

  tpm2-tss-engine:
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr
      - --host=$CRAFT_ARCH_TRIPLET
    build-environment:
      - LDFLAGS: "$LDFLAGS -Wl,-rpath-link,$CRAFT_STAGE/lib"
    source: https://github.com/tpm2-software/tpm2-tss-engine
    source-type: git
    source-tag: v1.1.0
    build-packages:
      - pandoc
      - pkg-config
      - gcc
      - autoconf-archive
      - autoconf
      - to amd64:
        - libtool
        - libssl-dev
      - to arm64:
        - libtool:arm64
        - libssl-dev:arm64
    after:
      - tpm2-tss

  webserver:
    plugin: dump
    source: webserver
    organize:
      tpm2-webserver.sh: usr/bin/tpm2-webserver.sh

apps:
  tpm2-webserver:
    command: usr/bin/tpm2-webserver.sh
    daemon: simple
    restart-condition: always
    restart-delay: 5s
    plugs: [tpm2-socket, system-configuration, network, network-bind]
