name: sdk-tpm2-webserver
title: SDK TPM2 Webserver
base: core24
version: 1.0.0
summary: A snap containing a tpm2 based openssl server for ctrlX OS.
description: |
  This app demonstrates how you can access the TPM2.

grade: devel

contact: https://github.com/boschrexroth/ctrlx-automation-sdk
license: MIT
donation: https://github.com/boschrexroth/ctrlx-automation-sdk
issues: https://github.com/boschrexroth/ctrlx-automation-sdk/issues
source-code: https://github.com/boschrexroth/ctrlx-automation-sdk
website: https://github.com/boschrexroth/ctrlx-automation-sdk

confinement: strict

platforms:
  amd64:
  arm64:
    build-on: [amd64, arm64]
    build-for: [arm64]

plugs:
  tpm2-socket:
    interface: content
    content: tpm2-socket
    target: $SNAP_DATA/tpm2-socket
  system-configuration:
    interface: content
    content: system-configuration
    target: $SNAP_DATA/system-configuration
slots:
  package-certificates:
    interface: content
    content: package-certificates
    source:
      write:
        - $SNAP_COMMON/package-certificates/${CRAFT_PROJECT_NAME}
  package-assets:
    interface: content
    content: package-assets
    source:
      read:
        - $SNAP/package-assets/${CRAFT_PROJECT_NAME}

parts:
  configs:
    plugin: dump
    source: ./configs
    organize:
      "package-assets/*": package-assets/${CRAFT_PROJECT_NAME}/
  webserver:
    plugin: dump
    source: webserver
    stage-packages:
      - to amd64:
        - libcurl4
        - tpm2-tools
        - tpm2-openssl
      - to arm64:
        - libcurl4:arm64
        - tpm2-tools:arm64
        - tpm2-openssl:arm64
    organize:
      tpm2-webserver.sh: usr/bin/tpm2-webserver.sh

apps:
  tpm2-webserver:
    command: usr/bin/tpm2-webserver.sh
    daemon: simple
    restart-condition: always
    restart-delay: 5s
    plugs: [tpm2-socket, system-configuration, network, network-bind]
