name: sdk-py-client-sub
title: SDK Python Client Subscription
version: 1.0.0
summary: ctrlX Data Layer client subscription sample written in Python for ctrlX
description: |
  This sample demonstrates how to use ctrlX Data Layer subscriptions with Python
base: core22
confinement: strict
grade: stable

apps:
  client:
    command: bin/main.py
    plugs:
      - network
      - datalayer
    daemon: simple
    restart-condition: always
    passthrough:
      restart-delay: 30s

parts:
  client:
    plugin: python
    source: .
    stage-packages:
      - libzmq5
      - ctrlx-datalayer

plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer
