name: sdk-py-remote-debug
title: SDK Python Remote Debug
version: 1.0.0
summary: ctrlX Data Layer client demonstrates remote debugging on a ctrlX
description: |
  The sample demonstrates how remote debugging on a ctrlX can be done.
base: core22
confinement: strict
grade: stable

apps:
  app:
    command: bin/main.py
    plugs:
      - network
      - network-bind
      - datalayer
    daemon: simple

parts:
  app:
    plugin: python
    source: .
    stage-packages:
      - libzmq5
      - ctrlx-datalayer

plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer
