name: sdk-py-remote-debug
title: SDK Python Remote Debug
version: 1.0.0
summary: ctrlX Data Layer client demonstrates remote debugging on a ctrlX
description: |
  The sample demonstrates how remote debugging on a ctrlX can be done.
base: core22
confinement: strict
grade: stable

architectures:
  - build-on: [amd64, arm64]
    build-for: [amd64]
  - build-on: [amd64, arm64]
    build-for: [arm64]

apps:
  app:
    command: bin/main.py
    plugs:
      - network
      - network-bind
      - datalayer
    daemon: simple

parts:
  app:
    plugin: python
    source: .
    stage-packages:
      - ctrlx-datalayer

plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer

lint:
  ignore:
    - library:
      - usr/lib/aarch64-linux-gnu/libcomm_datalayer.so.*
      - usr/lib/x86_64-linux-gnu/libcomm_datalayer.so.*
