# Getting started
# See https://snapcraft.io/docs/getting-started
# Snapcraft references
# See https://snapcraft.io/docs/snapcraft-yaml-reference

name: sdk-cpp-helloplc
version: "2.2.0"
grade: stable
summary: Write PLC variables
description: |
  This app determines symbolic PLC variables from plc-program 'PLC_PRG' and writes in all variables of
  the type string 'HelloDeveloper', in all integers '1337' and in all floats the value '0.815f'.
base: core22
confinement: strict

# define how apps & services are exposed to host system
apps:
  helloPlc:
    command: helloPlc
    # interfaces to connect to https://snapcraft.io/docs/supported-interfaces
    plugs:
    - network
    - datalayer
    daemon: simple
    passthrough:
      restart-condition: always
      restart-delay: 10s


#  describes how to import, and potentially build, each required part of the snap:
parts:
  helloplc:
    plugin: dump
    source: ./generated/build
    stage-packages:
      - libzmq5
      - ctrlx-datalayer

# describes which interface slots are supported by defining the plugs
plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer
