# Getting started
# See https://snapcraft.io/docs/getting-started
# Snapcraft references
# See https://snapcraft.io/docs/snapcraft-yaml-reference

name: sdk-cpp-hello-plc
title: SDK C++ Hello PLC
version: 1.0.0
grade: stable
summary: Write PLC variables
description: |
  This app determines symbolic PLC variables from plc-program 'PLC_PRG' and writes in all variables of
  the type string 'HelloDeveloper', in all integers '1337' and in all floats the value '0.815f'.
base: core22
confinement: strict

architectures:
  - build-on: [amd64, arm64]
    build-for: [amd64]
  - build-on: [amd64, arm64]
    build-for: [arm64]

# define how apps & services are exposed to host system
apps:
  app:
    command: helloPlc
    # interfaces to connect to https://snapcraft.io/docs/supported-interfaces
    plugs:
      - network
      - datalayer
    daemon: simple
    restart-condition: always
    passthrough:
      restart-delay: 10s

#  describes how to import, and potentially build, each required part of the snap:
parts:
  helloplc:
    plugin: dump
    source: ./generated/build
    stage-packages:
      - ctrlx-datalayer

# describes which interface slots are supported by defining the plugs
plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer

lint:
  ignore:
    - library:
      - usr/lib/aarch64-linux-gnu/libcomm_datalayer.so.*
      - usr/lib/x86_64-linux-gnu/libcomm_datalayer.so.*
