# Getting started
# See https://snapcraft.io/docs/getting-started

# Snapcraft references
# See https://snapcraft.io/docs/snapcraft-yaml-reference

name: sdk-net-logbook
title: SDK .NET Logbook
base: core22
version: 1.0.0
#icon: assets/icons/ICONHERE.png
summary: Logbook sample written in .NET for ctrlX OS.
description: |
  Program is logging messages to the logbook of the ctrlX OS.
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: [amd64, arm64]
    build-for: [amd64]
  - build-on: [amd64, arm64]
    build-for: [arm64]

apps:
  app:
    command: diagnostics.logbook
    daemon: simple
    restart-condition: always
    passthrough:
      restart-delay: 10s

    environment:
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 'true'

parts:
  app:
    plugin: dump
    source: ./publish
