// automatically generated by the FlatBuffers compiler, do not modify

package pkg.sample.schema

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class InertialValue : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : InertialValue {
        __init(_i, _bb)
        return this
    }
    val x : Short
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getShort(o + bb_pos) else 0
        }
    val y : Short
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getShort(o + bb_pos) else 0
        }
    val z : Short
        get() {
            val o = __offset(8)
            return if(o != 0) bb.getShort(o + bb_pos) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsInertialValue(_bb: ByteBuffer): InertialValue = getRootAsInertialValue(_bb, InertialValue())
        fun getRootAsInertialValue(_bb: ByteBuffer, obj: InertialValue): InertialValue {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createInertialValue(builder: FlatBufferBuilder, x: Short, y: Short, z: Short) : Int {
            builder.startTable(3)
            addZ(builder, z)
            addY(builder, y)
            addX(builder, x)
            return endInertialValue(builder)
        }
        fun startInertialValue(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addX(builder: FlatBufferBuilder, x: Short) = builder.addShort(0, x, 0)
        fun addY(builder: FlatBufferBuilder, y: Short) = builder.addShort(1, y, 0)
        fun addZ(builder: FlatBufferBuilder, z: Short) = builder.addShort(2, z, 0)
        fun endInertialValue(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
        fun finishInertialValueBuffer(builder: FlatBufferBuilder, offset: Int) = builder.finish(offset)
        fun finishSizePrefixedInertialValueBuffer(builder: FlatBufferBuilder, offset: Int) = builder.finishSizePrefixed(offset)
    }
}
