# Getting started
# See https://snapcraft.io/docs/getting-started
# Snapcraft references
# See https://snapcraft.io/docs/snapcraft-yaml-reference
name: ctrlx-dotnet-appdata
version: '1.0.0'
summary: Application data sample written in .NET for ctrlX.
description: |
  The sample demonstrates how to persist your application data inside ctrlX environment.
confinement: strict
#confinement: devmode
#icon: assets/icons/ICONHERE.png
grade: stable  # must be 'stable' to release into candidate/stable channels
base: core18
type: app

apps:
  app:
    command: appdata
    # interfaces to connect to https://snapcraft.io/docs/supported-interfaces
    plugs: [network, network-status, network-bind, process-control]
    daemon: simple
    restart-condition: always
    passthrough:
      restart-delay: 10s

    environment:
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 'true'

parts:
  app:
    plugin: dump
    source: ./generated

  configs:
    source: ./configs
    plugin: dump
    organize:
      'package-assets/*': package-assets/${SNAPCRAFT_PROJECT_NAME}/

slots:
  package-assets:
    interface: content
    content: package-assets
    source:
      read:
      - $SNAP/package-assets/${SNAPCRAFT_PROJECT_NAME}
  package-run:
    interface: content
    content: package-run
    source:
      write:
      - $SNAP_DATA/package-run/${SNAPCRAFT_PROJECT_NAME}

# describes which interface slots are supported by defining the plugs
plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer
    
  active-solution:
    interface: content
    content: solutions
    target: $SNAP_COMMON/solutions