name: sdk-py-appdata
title: SDK Python App Data
version: 1.0.0
summary: Application data sample written in Python for ctrlX
description: |
  This sample demonstrates how to persist your application data in ctrlX OS

base: core22
confinement: strict
grade: stable

architectures:
  - build-on: [amd64, arm64]
    build-for: [amd64]
  - build-on: [amd64, arm64]
    build-for: [arm64]

apps:
  appdata:
    command: bin/main.py
    plugs:
      - network-bind
      - active-solution
    slots:
      - package-assets
      - package-run
    daemon: simple

parts:
  appdata:
    plugin: python
    source: .

  configs:
    source: ./configs
    plugin: dump
    organize:
      'package-assets/*': package-assets/${CRAFT_PROJECT_NAME}/

slots:
  package-assets:
    interface: content
    content: package-assets
    source:
      read:
        - $SNAP/package-assets/${CRAFT_PROJECT_NAME}
  package-run:
    interface: content
    content: package-run
    source:
      write:
        - $SNAP_DATA/package-run/${CRAFT_PROJECT_NAME}

plugs:
  active-solution:
    interface: content
    content: solutions
    target: $SNAP_COMMON/solutions
