# Getting started
# See https://snapcraft.io/docs/getting-started
# Snapcraft references
# See https://snapcraft.io/docs/snapcraft-yaml-reference
name: sdk-node-client-browse
title: SDK Node.js Client Browse
version: 1.0.0
summary: ctrlX Data Layer browse sample written in Node.js for ctrlX OS.
description: |
  The sample app shows how to browse the ctrlX Data Layer.
confinement: strict
#confinement: devmode
#icon: assets/icons/ICONHERE.png
grade: stable

contact: https://github.com/boschrexroth/ctrlx-automation-sdk
license: MIT
donation: https://github.com/boschrexroth/ctrlx-automation-sdk
issues: https://github.com/boschrexroth/ctrlx-automation-sdk/issues
source-code: https://github.com/boschrexroth/ctrlx-automation-sdk
website: https://github.com/boschrexroth/ctrlx-automation-sdk

base: core24
type: app

platforms:
  amd64:
  arm64:
    build-on: [amd64, arm64]
    build-for: [arm64]

apps:
  app:
    command: bin/app
    daemon: simple
    # interfaces to connect to https://snapcraft.io/docs/supported-interfaces
    plugs:
      - network
      - datalayer
    restart-condition: always
    passthrough:
      restart-delay: 10s

parts:
  app:
    source: .
    build-environment:
      # Set the node version here. We recommend to use the latest LTS version.
      - NODE_VERSION: "24.14.0"

    # We don't use the npm plugin here, because it has no X-build capability (can't build arm64 target snaps on amd64).
    # plugin: npm
    # npm-node-version: "24.14.0"
    plugin: nil
    override-build: |
    
      $SNAPCRAFT_PROJECT_DIR/../build-node-app.sh
      craftctl default

# describes which interface slots are supported by defining the plugs
plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer
    
lint:
  ignore:
    - library:
      - bin/node
      - lib/node_modules/$CRAFT_PROJECT_NAME/node_modules/ctrlx-datalayer/prebuilds/linux-$CRAFT_ARCH_BUILD_FOR/ctrlx-datalayer.node
