# Getting started
# See https://snapcraft.io/docs/getting-started
# Snapcraft references
# See https://snapcraft.io/docs/snapcraft-yaml-reference

name: sdk-cpp-provider-simple
title: SDK C++ Provider Simple
version: 1.0.0
grade: stable
summary: Sample app in cpp to register a ctrlX Data Layer branch with several nodes
description: |
  This app will create a ctrlX Data Layer branch 'sdk/cpp/datalayer/provider/simple/' with nodes of different data types.
base: core22
confinement: strict

# define how apps & services are exposed to host system
apps:
  app:
    command: datalayerProviderSimple
    # interfaces to connect to https://snapcraft.io/docs/supported-interfaces
    plugs:
      - network
      - datalayer
    daemon: simple
    passthrough:
      restart-condition: always
      restart-delay: 10s

parts:
  app:
    plugin: dump
    source: ./generated/build
    stage-packages:
      - libzmq5
      - ctrlx-datalayer

  compiled:
    plugin: dump
    # metadata.mddb, sampleSchema.bfbs
    source: ./compiled

# describes which interface slots are required by defining the plugs
plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer
