# See https://snapcraft.io/docs/getting-started
# See https://snapcraft.io/docs/snapcraft-yaml-reference
name: sdk-multi-language
version: '1.0.0'
base: core22
title: SDK Multi-language
summary: Multi-language sample in Angular for ctrlX
description: |
  This sample shows how to set different languages in Third-party apps.
grade: stable         # must be 'stable' to release into candidate/stable channels
confinement: strict   # reduced file access to selected areas, reduced

parts:
  configs:
    source: ./configs
    plugin: dump
    organize:
      'package-assets/*': package-assets/${SNAPCRAFT_PROJECT_NAME}/

  www:
    source: .
    plugin: npm
    npm-node-version: '14.15.0'
    override-build: |
      # install node
      snapcraftctl build

      # setup npm
      npm config set unsafe-perm true

      # install dependencies
      npm install

      # run angular build script
      npm run build

      # remove node
      rm -rf ${SNAPCRAFT_PART_INSTALL}
    organize:
      '${SNAPCRAFT_PART_BUILD}/dist/app': package-www/${SNAPCRAFT_PROJECT_NAME}/

slots:
  package-assets:
    interface: content
    content: package-assets
    source:
      read:
      - $SNAP/package-assets/${SNAPCRAFT_PROJECT_NAME}

  package-www:
    interface: content
    content: package-www
    source:
      read:
      - $SNAP/package-www/${SNAPCRAFT_PROJECT_NAME}
