name: sdk-py-webserver
title: SDK Python Web Server
version: 1.0.0
summary: Web server Sample written in Python for ctrlX
description: |
  This sample shows how to create a web server app in ctrlX
base: core22
confinement: strict
grade: stable

architectures:
  - build-on: [amd64, arm64]
    build-for: [amd64]
  - build-on: [amd64, arm64]
    build-for: [arm64]

apps:
  webserver:
    command: bin/main.py
    plugs:
      - network-bind
      - active-solution
      - datalayer
    slots:
      - package-assets
      - package-run
    daemon: simple

parts:
  webserver:
    plugin: python
    source: .
    stage-packages:
      - ctrlx-datalayer
      - libsystemd-dev
      - libzmq5

  configs:
    plugin: dump
    source: ./configs
    organize:
      'package-assets/*': package-assets/${CRAFT_PROJECT_NAME}/

  www:
    plugin: dump
    source: ./www
    organize:
      '*': www/

slots:
  package-assets:
    interface: content
    content: package-assets
    source:
      read:
        - $SNAP/package-assets/${CRAFT_PROJECT_NAME}
  package-run:
    interface: content
    content: package-run
    source:
      write:
        - $SNAP_DATA/package-run/${CRAFT_PROJECT_NAME}

plugs:
  active-solution:
    interface: content
    content: solutions
    target: $SNAP_COMMON/solutions
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer
